DROP TABLE IF EXISTS followings;
DROP TABLE IF EXISTS special_comments;
DROP TABLE IF EXISTS special_posts;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS trees;